// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADWh6Ma1xVTZd7eru8jrlDBCcIy4RzWWo',
    appId: '1:497984250500:web:6d2ea237a3ae0753cc98d1',
    messagingSenderId: '497984250500',
    projectId: 'ssbsafetyapplication',
    authDomain: 'ssbsafetyapplication.firebaseapp.com',
    storageBucket: 'ssbsafetyapplication.appspot.com',
    measurementId: 'G-NCKLN0NSS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvfaSYgWqRfFOu9z9JAfx0Gkm2tDzZlCg',
    appId: '1:497984250500:android:49d84a1f6fba72d8cc98d1',
    messagingSenderId: '497984250500',
    projectId: 'ssbsafetyapplication',
    storageBucket: 'ssbsafetyapplication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjd3U0BhGVBW0GPcYdHJJTGP5bmxvA_P0',
    appId: '1:497984250500:ios:ed77ab19f9fbef13cc98d1',
    messagingSenderId: '497984250500',
    projectId: 'ssbsafetyapplication',
    storageBucket: 'ssbsafetyapplication.appspot.com',
    iosClientId: '497984250500-obkrocn3n4udj6e0pf5n6pagprrabn4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.safetyapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjd3U0BhGVBW0GPcYdHJJTGP5bmxvA_P0',
    appId: '1:497984250500:ios:56234b21f731d6d0cc98d1',
    messagingSenderId: '497984250500',
    projectId: 'ssbsafetyapplication',
    storageBucket: 'ssbsafetyapplication.appspot.com',
    iosClientId: '497984250500-05pe0mj987eqj659i7k0bubejld0ptfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.safetyapps.RunnerTests',
  );
}
